redis:
  image: redis

webclient:
  build: ./client
  volumes:
    - ./client/dist:/usr/share/nginx/html:ro
  ports:
    - "80:80"

redis-ws-relay:
  build: ./redis-ws-relay
  command: uwsgi --ini uwsgi.ini
  volumes:
    - ./redis-ws-relay:/code
  ports:
    - "9000:9000"
  links:
    - redis

workers:
  build: ./workers
  command: python thingzone.py
  volumes:
    - ./workers:/code
  links:
    - redis
